- ui/karma-config.js
- ui/package.json
In order to show proper line number for errors.
> Added sourcemaps for karma tests bundled with webpack

- backend/src/test/scala/com/softwaremill/bootzooka/test/BaseRoutesSpec.scala
- build.sbt
- project/build.properties
- Update build configuration since some sbt features are deprecated
> Switch to sbt 0.13.13

- index.md
> fix tiny typo in index.md

- .travis.yml
- backend/src/main/scala/com/softwaremill/bootzooka/common/sql/SqlDatabase.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/application/UserService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/domain/User.scala
- build.sbt
- project/build.properties
Also upgrade libraries:
- akka 2.5.0
- akka-http 10.0.0.5
- akka-http-session 0.4.0
- slick 3.2.0
- scalatest 3.0.1
- circe 0.7.0
and use sbt 0.13.15
> Upgrade to Scala 2.12

- devtips.md
> Added documentation related to Swagger integration

- backend/src/main/resources/reference.conf
- backend/src/main/scala/com/softwaremill/bootzooka/DependencyWiring.scala
- backend/src/main/scala/com/softwaremill/bootzooka/common/Salt.scala
- backend/src/main/scala/com/softwaremill/bootzooka/common/Utils.scala
- backend/src/main/scala/com/softwaremill/bootzooka/common/crypto/Argon2dPasswordHashing.scala
- backend/src/main/scala/com/softwaremill/bootzooka/common/crypto/CryptoConfig.scala
- backend/src/main/scala/com/softwaremill/bootzooka/common/crypto/PasswordHashing.scala
- backend/src/main/scala/com/softwaremill/bootzooka/common/crypto/Salt.scala
- backend/src/main/scala/com/softwaremill/bootzooka/passwordreset/application/PasswordResetService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/application/UserDao.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/application/UserService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/domain/User.scala
- backend/src/test/scala/com/softwaremill/bootzooka/common/crypto/Argon2dPasswordHashingSpec.scala
- backend/src/test/scala/com/softwaremill/bootzooka/passwordreset/api/PasswordResetRoutesSpec.scala
- backend/src/test/scala/com/softwaremill/bootzooka/passwordreset/application/PasswordResetServiceSpec.scala
- backend/src/test/scala/com/softwaremill/bootzooka/test/TestHelpers.scala
- backend/src/test/scala/com/softwaremill/bootzooka/test/TestHelpersWithDb.scala
- backend/src/test/scala/com/softwaremill/bootzooka/user/EncryptPasswordBenchmark.scala
- backend/src/test/scala/com/softwaremill/bootzooka/user/application/UserDaoSpec.scala
- backend/src/test/scala/com/softwaremill/bootzooka/user/application/UserServiceSpec.scala
- backend/src/test/scala/com/softwaremill/bootzooka/user/domain/UserSpec.scala
- build.sbt
Updates several pieces of the application so that password storage is actually safe in 2017.
The following things were changed/added:
- using SecureRandom instead of Random
- using modern hash function (Argon2 was chosen)
- resetting salt along password reset
- configuration of Argon2 was added
- when above mentioned configuration changes and user logs in then the password is rehashed with new values from configuration and a new salt
> #114 Security update of password storage

- build.sbt
> [Proposal] Clean the `ui/build` dir on `sbt clean` command

- build.sbt
> `otj-pg-embedded` should not be packaged with the production app

- backend/src/main/scala/com/softwaremill/bootzooka/http/HttpApi.scala
If you use Bootzooka as a standalone server containing static frontend files, reloading any page other than the root page (`/`) will result in a 404 error. (Issue #213)
This PR fixes it. 
**How it works:**
If route has not been found server should send response with `webapp/index.html` content but with original headers from request.
**Test it:**
1. Build and run application using following commands:
```
git clone https://github.com/char16t/bootzooka bootzooka-fix213
cd bootzooka-fix213
git checkout char16t-fix213
sbt docker:publishLocal
docker-compose up
```
2. Go to http://localhost:8080 and press F5 to reload page
3. Click to any link in header and press F5 to reload page
4. Try to login (check API calls)
> Fix 404 on reload any non-root page

- docs/testing.md
- integration-tests/docker-compose.yml
This pr allows us to test sending emails by SMTP server.
> Added docker compose integrated with mailhog for testing purposes

- README.md
Updated CI status badge - linking to renamed Bootzook'a CI workflow
> Updated CI status badge

- .github/workflows/bootzooka-helm-ci.yaml
'helm-docs-action' repo transfer
> 'helm-docs-action' repo transfer

- backend/src/main/scala/com/softwaremill/bootzooka/email/EmailService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/passwordreset/PasswordResetApi.scala
- backend/src/main/scala/com/softwaremill/bootzooka/passwordreset/PasswordResetService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/security/ApiKeyService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/UserService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/util/IdGenerator.scala
IdGenerator returns Task instead of unwrapped Id
> Changing Id generation to monix's Task

- backend/src/main/scala/com/softwaremill/bootzooka/MainModule.scala
- backend/src/main/scala/com/softwaremill/bootzooka/passwordreset/PasswordResetService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/security/ApiKeyService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/security/Auth.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/UserService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/util/BaseModule.scala
- backend/src/test/scala/com/softwaremill/bootzooka/test/TestClock.scala
- backend/src/test/scala/com/softwaremill/bootzooka/user/UserApiTest.scala
- build.sbt
> Added Clock[IO] as implementation of clock

- project/RenameProject.scala
the issue was it was trying to access some locked file in node_modules
> fix sbt RenameProject

- backend/src/main/scala/com/softwaremill/bootzooka/http/HttpApi.scala
Just simple removal of resourceService usage in HttpApi
> Remove deprecated resourceService usage

- backend/src/main/scala/com/softwaremill/bootzooka/Dependencies.scala
- backend/src/main/scala/com/softwaremill/bootzooka/Main.scala
- backend/src/main/scala/com/softwaremill/bootzooka/email/EmailService.scala
- backend/src/test/scala/com/softwaremill/bootzooka/test/TestDependencies.scala
- build.sbt
This PR simplifies running the application a bit as well as running background processes, like `emailService`.
> Run App as ResourceApp

- backend/src/main/resources/logback.xml
> Fix logback.xml

- ui/package.json
* It fix ui build bug. More: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
> Add openssl-legacy-provider to package.json

- backend/src/main/scala/com/softwaremill/bootzooka/security/ApiKeyModel.scala
- backend/src/main/scala/com/softwaremill/bootzooka/security/ApiKeyService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/UserApi.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/UserService.scala
- backend/src/test/scala/com/softwaremill/bootzooka/test/Requests.scala
- backend/src/test/scala/com/softwaremill/bootzooka/user/UserApiTest.scala
- ui/src/main/Top/Top.test.tsx
- ui/src/main/Top/Top.tsx
- ui/src/pages/Profile/components/PasswordDetails.test.tsx
- ui/src/pages/Profile/components/PasswordDetails.tsx
- ui/src/services/UserService/UserService.test.ts
- ui/src/services/UserService/UserService.ts
This PR introduces security enhancements in authentication and session management processes.
- on **logout**, the user's token is invalidated and removed from database
- on **password change**, all user's token are invalidated and removed from database
> Invalidate session on password change/logout

- build.sbt
- docs/production.md
> Fix sbt-assembly

- backend/src/main/scala/com/softwaremill/bootzooka/infrastructure/DB.scala
- backend/src/main/scala/com/softwaremill/bootzooka/infrastructure/Magnum.scala
- backend/src/main/scala/com/softwaremill/bootzooka/security/ApiKeyService.scala
- backend/src/main/scala/com/softwaremill/bootzooka/security/Auth.scala
- backend/src/main/scala/com/softwaremill/bootzooka/user/UserModel.scala
- build.sbt
> Update Magnum to 1.3.1 and use SqlLogger.logSlowQueries

- .github/dependabot.yml
> Add automatic JS dependency update
